### ISSUE TITLE
Factory methods

### ISSUE THREAD

**Issue by hpehl** [patternfly-java/patternfly-java#1]
PatternFly / Java uses factory methods to create components:

```java
import org.patternfly.client.components.Alert;
import org.patternfly.client.components.Avatar;
import static org.patternfly.client.components.Components.avatar;

Avatar avatar = avatar("./images/img_avatar.svg", "avatar");
Alert info = Alert.info("Info inline alert title");
```

At the moment these factory methods are spread across different classes:

- for components with few variations (like `Avatar`), the factory methods live in `org.patternfly.client.components.Components`
- for components with many different variations (like `Alert` or `Button`), the factory methods are part of the component itself. 

This issue is about where to place the factory methods:

[![](https://api.gh-polls.com/poll/01DT96V056K9TDFTPZWHJ8782Q/Some%20in%20Components%2C%20some%20in%20the%20component%20itself)](https://api.gh-polls.com/poll/01DT96V056K9TDFTPZWHJ8782Q/Some%20in%20Components%2C%20some%20in%20the%20component%20itself/vote)
[![](https://api.gh-polls.com/poll/01DT96V056K9TDFTPZWHJ8782Q/All%20in%20Components)](https://api.gh-polls.com/poll/01DT96V056K9TDFTPZWHJ8782Q/All%20in%20Components/vote)
[![](https://api.gh-polls.com/poll/01DT96V056K9TDFTPZWHJ8782Q/All%20in%20the%20component%20itself)](https://api.gh-polls.com/poll/01DT96V056K9TDFTPZWHJ8782Q/All%20in%20the%20component%20itself/vote)

**Comment by RaulPampliegaMayoral** [comment]
i like more to have the factory methods all in the component itself. It's a bit clear for me to know which and where is the component.

**Comment by lofidewanto** [comment]
Object oriented design and please no anemic domain model: the component has the ability / "behaviour" to create itself. No procedural design like Services and Entities please.

**Comment by hpehl** [comment]
@lofidewanto So you opt for 3) "All in the component itself" or 4) "Get rid of all factory methods and just use overloaded constructors"?

**Comment by hpehl** [comment]
The reason for using factory methods is that IMO it leads to more readable code. Together with static imports, it reflects more the structure of the UI / DOM tree.

**Comment by lofidewanto** [comment]
Using overloaded constructor is surely the most OO way... This is what you mean with "reflects the structure of UI / DOM"?

`Alert info = Alert.info("Info inline alert title");`

or this one?

`Alert info = info("Info inline alert title");`

Both are not really OO like:

`Alert info = new Alert("Info inline alert title");`

But you are right, this one would be very similar to DOM UI also similar to SwiftUI or TornadoFX:

`Alert info = info("Info inline alert title");`

or

`Alert info = alert("Info inline alert title");`

This would be very similar to DOM UI / SwiftUI / TornadoFX. 

I would prefer the last one which is very similar to DOM UI / SwiftUI / TornadoFX.

**Comment by hpehl** [comment]
I prefer static factory methods over constructors because code becomes more readable when you build large structures of nested components. In this case constructors would "pollute" the code with lots of `new Foo()`, `new Bar()` and `new YetAnotherThing()` statements.

Another decision is whether to provide one (overloaded) factory method with many different parameters /  vs. multiple factory methods with less parameters. As rule of thumb I distinguish between variations and modifications: 

1. Variations
Alerts and buttons are examples of this category. They come in different variations like info, warning or errors for alerts and normal button, link or control for buttons. In that case I try to provide different factory methods.

1. Modifications
A dropdown can be modified to open up or a card can be compact. In that case there are instance methods to modify the component.

I'd like to get feedback whether this approach makes sense to you.

**Comment by lofidewanto** [comment]
@hpehl agree with you with "new" vs. Builder Pattern. But also in Builder Pattern you have alternatives like what I've shown up there. Which one do you think better?

With Variations and Modifications: I'm not sure whether I understand you. Maybe example?

**Comment by hpehl** [comment]
The button component is a pretty good example what I mean with variations vs. modification. Buttons come in different variations:

- normal buttons
- links
- icons
- controls

```java
import static org.patternfly.client.resources.CSS.fas;

Button button = Button.button("Button");
Button link = Button.link("Liunk");
Button icon = Button.icon(fas("chart-pie"), "Chart");
Button control = Button.control("Control");
```

For normal buttons there are different variations:

- primary
- secondary
- tertiary
- danger

```java
Button primary = Button.button("Primary").primary();
Button secondary = Button.button("Secondary").secondary();
Button tertiary = Button.button("Tertiary").tertiary();
Button danger = Button.button("Danger").danger();
```

It's not always 100% clear where to draw the line between variations and modifications. I hope I found a good balance in the API so far.

**Comment by lofidewanto** [comment]
@hpehl Looks good! I opt for the Button examples 👍

**Comment by baldram** [comment]
Here is one input to the discussion ;-) Previous proposals are good. Just another option to be considered.
As the fluent API is used here there is another possibility. It gives a consistent rule for component attributes like: type, variation. Based on above examples, please find them slightly modified:

```java
import static org.patternfly.client.resources.CSS.fas;

Button primary = Button.of("Primary").button().primary();
// ... secondary, ... tertiary
Button secondary = Button.of("Secondary").button().danger();
Button link = Button.of("Link").link();
Button icon = Button.of(fas("chart-pie"), "Chart").icon();
Button control = Button.of("Control").control();
```
So it is a generic and clean API which should fit to complex and simple requirements if about components. What do you think?

**Comment by lofidewanto** [comment]
I'm not sure whether I like: 
`Button primary = Button.of("Primary").button().primary();`
... because if I make a static import I'll see following:
`Button primary = of("Primary").button().primary();`
...
This is better:
`Button primary = button("Primary").primary();`

**Comment by baldram** [comment]
I get your point @lofidewanto. My assumption was that `Button.of` is short enough so that static import is not needed. Then other elements are lets say `Avatar.of`, `CheckBox.of` and so on. 
It's the same concept as `Stream.of`, `Optional.of`, `LocalDateTime.of`, `ZonedDateTime.of`, `List.of` and so on. For them you rather avoid static imports. On the other hand I understand your point. 
As in the example [here](https://patternfly-java.github.io/showcase/#/showcase/documentation/button) it is simple:
```java
Button b05 = button("Primary icon").primary().withIcon(fas("address-card")));
```
Further when it gets to more complex use case like [the 2nd example here](https://patternfly-java.github.io/showcase/#/showcase/documentation/data-list), this static import might be an advantage. However, mentioned 2nd example has this even longer version `Button.button("Primary")` and it's still readable. So `Button.of` vs `button` would be a bit longer but not much worse. 
But, as I mentioned, I agree that in case of complex definition, shortness is an advantage.

**Comment by hpehl** [comment]
Thanks for your input. I'll move all static factory methods into the component classes. For the moment I'll stick with the current factory methods.

**Comment by hpehl** [comment]
Done with https://github.com/patternfly-java/patternfly-java/commit/a42620d2df9198bd092ae15c7e4ed4bb0b279945
