### ISSUE TITLE
TextInput password type is missing

### ISSUE THREAD

**Issue by kolka213** [patternfly-java/patternfly-java#197]
I noticed while creating a basic form that the factory method 
`TextInput password = textInput(TextInputType.password, "password");`
will create a regular textfield with "text" as type attribute.

Reason for that:
The type mapping HashMap in the TextInput.class does not contain TextInputType.password as a key, so when the input element is created `input(typeMapping.getOrDefault(type, InputType.text)` , it will default to text.

One workaround I found was this:
`password.element().firstElementChild.setAttribute("type", "password");`.
since the input element is inside the TextField div.

If possible I'd like to contribute to that issue.

Version: 0.2.5

**Comment by hpehl** [comment]
Good catch! You can fix this by adding the missing key to the hashmap. Feel free to submit a PR, and I'll be happy to merge it!

**Comment by hpehl** [comment]
Fixed by #198
