### ISSUE TITLE
Some confusion about the code implementation.

### ISSUE THREAD

**Issue by raindroplvy** [patternfly-java/patternfly-java#200]
I have a question. The extension  ui components of patternfly-java are implemented by wrapping the dom element, so why not inherit the dom element?  This preserves methords of the original dom element. Is it possible to implement something like this?

`class Badge extends HTMLElement
{
...
}`

**Comment by hpehl** [comment]
That might make sense for some components. I've chosen a different approach by having a common base class all components extend from: `BaseComponent<E extends HTMLElement, B extends TypedBuilder<E, B>>`

This base class provides the builder-like API from which all components benefit. At the same time, all components implement shared interfaces from [Elemento](https://github.com/hal/elemento) that help work with their base element: 

- [`HasElement<E, B>`](https://hal.github.io/elemento/apidocs/org/jboss/elemento/HasElement.html) and [`HasHTMLElement<E, B>`](https://hal.github.io/elemento/apidocs/org/jboss/elemento/HasHTMLElement.html) to manipulate the base element
- [`Finder<E>`](https://hal.github.io/elemento/apidocs/org/jboss/elemento/Finder.html) and [`Container<E, B>`](https://hal.github.io/elemento/apidocs/org/jboss/elemento/Container.html) to find and add nested elements

I agree that extending from the root element makes it easier to work with the root element, but at the same time, it prohibits some common functionality across all components.

**Comment by hpehl** [comment]
I filed #214 to address this. @raindroplvy if you have any questions, please ping me or re-open this issue with your question.
