### ISSUE TITLE
Implement backdrop component

### ISSUE THREAD

**Issue by hpehl** [patternfly-java/patternfly-java#22]
https://www.patternfly.org/components/backdrop/html

**Comment by halkosajtarevic** [comment]
how about this one? :)

**Comment by hpehl** [comment]
Perfect. Go for it!

**Comment by hpehl** [comment]
@halkosajtarevic Please note that with 0.2.0, the codebase has changed quite a lot: 

- Split the code into several modules
- Integrate the showcase into the main codebase

So please update/rebase your work before implementing the backdrop. If you have questions/issues, please let me know!

**Comment by halkosajtarevic** [comment]
sorry, didn't manage yet to take a look, will do it within the next weeks! hope it's not an issue for you?

**Comment by hpehl** [comment]
No worries. However, I implemented the backdrop component in the meantime (it was a requirement for the modal component, which I implemented recently). 

But there are plenty of other components waiting for an implementation 😉 So just pick one you would like to implement and let me know if you have questions.
