### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by zzj1213** [patternfly-java/patternfly-java#3]
[ERROR] Failed to execute goal on project patternfly-java: Could not resolve dependencies for project org.patternfly:patternfly-java:jar:2.43.1: The following artifacts could not be resolved: org.jboss.elemento:elemento-core:jar:HEAD-SNAPSHOT, org.junit.jupiter:junit-jupiter:jar:5.0.3, org.mockito:mockito-core:jar:3.3.11: Could not find artifact org.jboss.elemento:elemento-core:jar:HEAD-SNAPSHOT ->

what is the right .m2/setting.xml ?

**Comment by hpehl** [comment]
PatternFly Java is wip and uses the latest Elemento builds. 

Please try to checkout and build Elemento locally: https://github.com/hal/elemento. This should fix the broken build.

**Comment by zzj1213** [comment]
use the local Elementary build works, thx.
