### ISSUE TITLE
Implement panel component

### ISSUE THREAD

**Issue by hpehl** [patternfly-java/patternfly-java#77]
https://www.patternfly.org/components/panel/html

**Comment by halkosajtarevic** [comment]
would this one be available as a first "real" contribution issue? :)

**Comment by hpehl** [comment]
@halkosajtarevic sure! Don't hesitate to ask question on how to get started, about the codebase, or anything else. 

I've created https://github.com/patternfly-java/patternfly-java/blob/main/src/main/java/org/patternfly/component/TemplateComponent.java as a blueprint for implementing new components. 

Looking forward to your PR!
